clock: argument check

diff --git a/scripts/cmd/clock b/scripts/cmd/clock
--- a/scripts/cmd/clock
+++ b/scripts/cmd/clock
@@ -34,7 +34,14 @@ END=$2
 
 START=$(date --date="$START" +%s)
 END=$(date --date="$END" +%s)
-echo "Clock during [$(date -d @$START), $(date -d @$END))"
+
+if [ ! "$START" ] || [ "$END" ] ; then
+	echo "invalid input" >&2
+	show_help
+	exit 1
+else
+	echo "Clock during [$(date -d @$START), $(date -d @$END))"
+fi
 
 generate_project_table PJTABLE
 declare -A clock_per_project
