add precheck for issue's existence

diff --git a/scripts/cmd/edit b/scripts/cmd/edit
--- a/scripts/cmd/edit
+++ b/scripts/cmd/edit
@@ -50,6 +50,7 @@ if [[ "$ISSUEID" =~ ^L ]] ; then
 	exit 0
 fi
 
-update_local_cache || exit 1
+update_local_cache_task $ISSUEID || exit 1
+! check_issue_exist $ISSUEID && echo "issue $ISSUEID not found" && exit 1
 
 update_issue3 $ISSUEID
diff --git a/scripts/cmd/remove b/scripts/cmd/remove
--- a/scripts/cmd/remove
+++ b/scripts/cmd/remove
@@ -23,6 +23,7 @@ if [[ "$ISSUEID" =~ ^L ]] ; then
 fi
 
 update_local_cache_task $ISSUEID || exit 1
+! check_issue_exist $ISSUEID && echo "issue $ISSUEID not found" && exit 1
 
 echo "You really remove issue $ISSUEID (subject: $(issueid_to_subject $ISSUEID))? (y: yes, n: no)"
 read input
diff --git a/scripts/cmd/show b/scripts/cmd/show
--- a/scripts/cmd/show
+++ b/scripts/cmd/show
@@ -47,7 +47,8 @@ if [[ "$ISSUEID" =~ ^L ]] ; then
 	exit
 fi
 
-update_local_cache || exit 1
+update_local_cache_task $ISSUEID || exit 1
+! check_issue_exist $ISSUEID && echo "issue $ISSUEID not found" && exit 1
 
 # TODO: better file name
 tmpjson=$TMPD/$ISSUEID/issue.json
