edit: introduce -f option
allows you to edit ticket from locally editted draft file.

Signed-off-by: Naoya Horiguchi <nao.horiguchi@gmail.com>

diff --git a/scripts/cmd/edit b/scripts/cmd/edit
--- a/scripts/cmd/edit
+++ b/scripts/cmd/edit
@@ -6,8 +6,14 @@
 # Description
 #   edit a specified ticket.
 #
+#   With -f option, edit a specified ticket by passing draft file,
+#   which are generated by `show` subcommand. Note that draft file
+#   shouldn't include notes, so switch off RM_SHOW_JOURNALS
+#   (to set blank or any string other than "true".)
+#
 # Options
 #   -r <note_id>  quote reply to the specified note
+#   -f <draft>    update ticket with given draft file
 #   -h            show this message
 #
 
@@ -16,12 +22,17 @@ show_help() {
 }
 
 REPLYNOTE=
+DRAFT=
 
 while [[ $# -gt 0 ]] ; do
 	key="$1"
 	case $key in
 		-r)
 			REPLYNOTE="$2"
+			shift 2
+			;;
+		-f)
+			DRAFT="$2"
 			shift 2
 			;;
 		-h)
@@ -36,19 +47,44 @@ done
 
 . $THISDIR/tree.sh
 
-ISSUEID=$1
+if [ "$DRAFT" ] ; then
+	if [ ! -s "$DRAFT" ] ; then
+		ehco "no DRAFT file found" >&2
+		exit 1
+	fi
 
-if ! check_ticket_id_format $ISSUEID ; then
-	echo "invalid issueid format" >&2
+	ISSUEID="$(grep -i ^#\+issue: $DRAFT | sed 's|^#+issue: *||i')"
+
+	if [ ! "$ISSUEID" ] ; then
+		echo "No issue ID in a given file" >&2
+		exit 1
+	fi
+
+	echo "Try to upload ticket with file $DRAFT for issue $ISSUEID"
+	upload_ticket $DRAFT $ISSUEID $TMPDIR/tmp.upload.json
+	if [ $? -eq 0 ] ; then
+		# TODO: need to download forcibly when you update relationship
+		# because timestamp might not be updated.
+		( update_local_cache_task $ISSUEID ) &
+		exit 0
+	fi
+	echo "update_issue failed, check draft.md and/or network connection."
 	exit 1
+else
+	ISSUEID=$1
+
+	if ! check_ticket_id_format $ISSUEID ; then
+		echo "invalid issueid format" >&2
+		exit 1
+	fi
+
+	if [[ "$ISSUEID" =~ ^L ]] ; then
+		edit_local_ticket $ISSUEID
+		exit 0
+	fi
+
+	update_local_cache_task $ISSUEID || exit 1
+	! check_issue_exist $ISSUEID && echo "issue $ISSUEID not found" && exit 1
+
+	update_issue3 $ISSUEID
 fi
-
-if [[ "$ISSUEID" =~ ^L ]] ; then
-	edit_local_ticket $ISSUEID
-	exit 0
-fi
-
-update_local_cache_task $ISSUEID || exit 1
-! check_issue_exist $ISSUEID && echo "issue $ISSUEID not found" && exit 1
-
-update_issue3 $ISSUEID
